In [42]:
import numpy as np

In [43]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [44]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 20.7 ms, sys: 2.23 ms, total: 22.9 ms
Wall time: 21.6 ms


In [45]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 414 ms, sys: 91.3 ms, total: 505 ms
Wall time: 505 ms


In [ ]:
l=[[1,3,4],[3,4,5]]
l

In [ ]:
l*2

In [ ]:
b=np.array(l)
b*2

In [ ]:
type(l)

In [ ]:
type(b)

In [46]:
np.ones((5,2,3))*5

array([[[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]]])

# Table 4.1

In [ ]:
import numpy as np

In [ ]:
a=[2,5,8]
np.array(a)

In [ ]:
a

In [ ]:
b=np.asarray(a)

In [ ]:
b[0]=33

In [ ]:
a

In [47]:
x=np.arange(24).reshape((2,3,4))
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
np.ones_like(x)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [49]:
np.full??

In [50]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [51]:
np.full_like(x, 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [52]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.identity??

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
l=[1,5,7]
b=np.array(l, dtype=np.int64)
c=np.array(l, dtype='i4')
print(b.dtype)
c.dtype

In [ ]:
type(2)

In [ ]:
type('2')

In [ ]:
a=np.array(['1','2'], dtype=np.string_)
a.dtype

In [ ]:
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([[7,0,5],
            [4,7,3]])
b > a

In [ ]:
b[b > a]

In [ ]:
i=np.array([[1,0,1],[1,1,0]], dtype='?')
i

In [ ]:
b[i]

In [ ]:
a=np.arange(10)
a

In [ ]:
a[5:8]=12

In [ ]:
a

In [ ]:
b=list(range(10))
b

In [ ]:
b[5:8]=10

In [ ]:
c=a[3:7]
c

In [ ]:
a

In [ ]:
c[0]=123431
c

In [ ]:
a

In [ ]:
id(c[0])

In [ ]:
id(a[3])

In [ ]:
id(a)

In [ ]:
b=a

In [ ]:
id(b)

In [ ]:
c=a[:]
id(c)

In [ ]:
d=a.copy()
id(d)

In [ ]:
a=np.arange(9).reshape((3,3))
a

In [ ]:
a[0] # first indice (row)

In [ ]:
a[1][1]

In [ ]:
a[1,1] # , indecate to indices (row, column)

In [ ]:
a=np.arange(1,13).reshape((2,2,3))
a

In [ ]:
a[1,0]

In [ ]:
a[1]

In [ ]:
b=np.arange(1,10).reshape((3,3))
b

In [ ]:
b[:2]

In [ ]:
b[:2, 1:]

In [ ]:
b[0, :2]

In [ ]:
b[:2,2]

In [ ]:
b[:,:1]

In [ ]:
b

In [ ]:
b[:2, 1:] = 0

In [ ]:
b

In [ ]:
c=np.arange(36).reshape((6,6))
c

In [ ]:
i=np.eye(6, dtype='?')
i

In [ ]:
c[i]

In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data = np.random.randn(7, 4)
data

array([[ 0.21825033,  0.84942277, -0.36936567, -2.07650594],
       [-0.69743076, -1.41387394,  1.0402712 ,  0.4244379 ],
       [-1.3367867 , -0.44140548,  0.07743543,  0.83644711],
       [-0.35591312, -0.1299656 , -0.4419226 ,  0.93067439],
       [-1.19066988, -1.1174121 , -0.61794619,  0.32062681],
       [-1.36561271, -0.4678318 ,  0.92392611, -0.51794184],
       [ 0.81708171,  0.3512302 , -1.22712984, -0.40897985]])

In [58]:
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.21825033  0.84942277 -0.36936567 -2.07650594]
 [-0.69743076 -1.41387394  1.0402712   0.4244379 ]
 [-1.3367867  -0.44140548  0.07743543  0.83644711]
 [-0.35591312 -0.1299656  -0.4419226   0.93067439]
 [-1.19066988 -1.1174121  -0.61794619  0.32062681]
 [-1.36561271 -0.4678318   0.92392611 -0.51794184]
 [ 0.81708171  0.3512302  -1.22712984 -0.40897985]]


In [59]:
i=names== 'Will'
i

array([False, False,  True, False,  True, False, False])

In [60]:
data[i]

array([[-1.3367867 , -0.44140548,  0.07743543,  0.83644711],
       [-1.19066988, -1.1174121 , -0.61794619,  0.32062681]])

In [61]:
data[:,i]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 7

In [62]:
data[names=="Bob", 2:]

array([[-0.36936567, -2.07650594],
       [-0.4419226 ,  0.93067439]])

In [63]:
data[names!='Bob']

array([[-0.69743076, -1.41387394,  1.0402712 ,  0.4244379 ],
       [-1.3367867 , -0.44140548,  0.07743543,  0.83644711],
       [-1.19066988, -1.1174121 , -0.61794619,  0.32062681],
       [-1.36561271, -0.4678318 ,  0.92392611, -0.51794184],
       [ 0.81708171,  0.3512302 , -1.22712984, -0.40897985]])

In [64]:
data[~(names=='Bob')]

array([[-0.69743076, -1.41387394,  1.0402712 ,  0.4244379 ],
       [-1.3367867 , -0.44140548,  0.07743543,  0.83644711],
       [-1.19066988, -1.1174121 , -0.61794619,  0.32062681],
       [-1.36561271, -0.4678318 ,  0.92392611, -0.51794184],
       [ 0.81708171,  0.3512302 , -1.22712984, -0.40897985]])

In [65]:
data[~(names=='Bob') | (names=='Will')]

array([[-0.69743076, -1.41387394,  1.0402712 ,  0.4244379 ],
       [-1.3367867 , -0.44140548,  0.07743543,  0.83644711],
       [-1.19066988, -1.1174121 , -0.61794619,  0.32062681],
       [-1.36561271, -0.4678318 ,  0.92392611, -0.51794184],
       [ 0.81708171,  0.3512302 , -1.22712984, -0.40897985]])

In [ ]:
a=np.zeros((8,4))
a

In [ ]:
for i in range(8):
    a[i]=i+1

In [ ]:
a

In [ ]:
a[[6,3,7]]

In [ ]:
a[:,[1,-1]]

In [ ]:
arr = np.arange(32).reshape((8,4)); arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
 arr[[1, 5, 7, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr

In [ ]:
arr.transpose()

In [ ]:
arr.transpose((1, 0, 2))

In [66]:
a= np.arange(1,11)
np.meshgrid(a, a)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

In [67]:
x = np.arange(1,11)
y = np.arange(11,21)
cond =[True, True, False,False,False,False,False,False,False,True]
print(x)
print(y)
cond

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


[True, True, False, False, False, False, False, False, False, True]

In [68]:
x[cond]

array([ 1,  2, 10])

In [70]:
[(x if c else y)
for x,c,y in zip(x,cond,y)
]

[1, 2, 13, 14, 15, 16, 17, 18, 19, 10]

In [71]:
np.where(True,'P','I')

array('P', dtype='<U1')

In [72]:
np.where(False,'P','I')

array('I', dtype='<U1')

In [73]:
np.where(cond, x, y)

array([ 1,  2, 13, 14, 15, 16, 17, 18, 19, 10])

In [74]:
a=np.random.randn(20)
a

array([ 0.27413879, -0.50625484, -0.65496138,  0.26530176, -2.53009007,
       -0.57030079, -0.63780737,  0.32939576,  0.59151394,  0.89384566,
       -0.14181381, -0.52463283, -0.28193145, -0.63960198, -0.18936729,
        0.6968201 ,  0.77960696,  0.10573269,  0.30358139, -0.14986647])

In [75]:
np.where(a<0, 0, a)

array([0.27413879, 0.        , 0.        , 0.26530176, 0.        ,
       0.        , 0.        , 0.32939576, 0.59151394, 0.89384566,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.6968201 , 0.77960696, 0.10573269, 0.30358139, 0.        ])

In [76]:
a[a>=1]

array([], dtype=float64)

In [81]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.mean()

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)

In [ ]:
{1,5,1,7,7,99}

In [ ]:
set([1,5,1,7,7,99])

In [ ]:
a=np.array([1,5,1,7,7,99])
np.unique(a)

In [ ]:
a=np.arange(25).reshape((5,5))
a

In [ ]:
np.diag(a)

In [ ]:
np.trace(a)

In [ ]:
a=np.arange(4).reshape((2,2))
a

In [ ]:
from numpy.linalg import det

In [ ]:
det(a)

In [ ]:
from random import normalvariate

In [ ]:
 N = 1000000

In [ ]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

In [ ]:
%timeit np.random.normal(size=N)