## 5.1 Tutorial Overview
This tutorial is divided into 4 parts; they are:
1. From List to Arrays
2. Array Indexing
3. Array Slicing
4. Array Reshaping

### 5.2.1 One-Dimensional List to Array

In [1]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


### 5.2.2 Two-Dimensional List of Lists to Array

In [2]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


### 5.3.1 One-Dimensional Indexing

In [3]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


In [4]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

One key difference is that you can use negative indexes to retrieve values offset from the end
of the array. For example, the index -1 refers to the last item in the array. The index -2 returns
the second last item all the way back to -5 for the first item in the current example.

In [5]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


### 5.3.2 Two-Dimensional Indexing

In [6]:
# index two-dimensional array
from numpy import array
# define array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
# index data
print(data[0,0])
print(data[1][1])

11
44


In [8]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]])
# index data
print(data[0,])
print(data[0,::])

[11 22]
[11 22]


This prints the first row of data.

### 5.4 Array Slicing

### 5.4.1 One-Dimensional Slicing

In [9]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [10]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [11]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


In [13]:
data[0:3]

array([11, 22, 33])

In [14]:
print(data[-2::-1])

[44 33 22 11]


### 5.4.2 Two-Dimensional Slicing

In [15]:
# split input and output data
from numpy import array
# define array
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### Split Train and Test Rows

In [16]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


### 5.5 Array Reshaping

### 5.5.1 Data Shape

NumPy arrays have a <b>shape</b> attribute that returns a tuple of the length of each dimension of
the array. For example:

In [17]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [19]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

print('Rows:', data.shape[0])

Rows: 3
Cols: 2
Rows: 3


### 5.5.2 Reshape 1D to 2D Array

In [22]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
print(data)
# reshape
#data = data.T
data = data.reshape((data.shape[0], 1))
print(data.shape)

data

(5,)
[11 22 33 44 55]
(5,)


array([11, 22, 33, 44, 55])

In [26]:
import numpy as np

a= np.arange(1,101).reshape((5,20))
print(a.shape)
print(a.T.shape)

(5, 20)
(20, 5)


### 5.5.3 Reshape 2D to 3D Array

In [27]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [28]:
data

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

In [33]:
a=np.arange(75).reshape((3,5,5))
print(a.shape)
a[:,::2, ::-1]

(3, 5, 5)


array([[[ 4,  3,  2,  1,  0],
        [14, 13, 12, 11, 10],
        [24, 23, 22, 21, 20]],

       [[29, 28, 27, 26, 25],
        [39, 38, 37, 36, 35],
        [49, 48, 47, 46, 45]],

       [[54, 53, 52, 51, 50],
        [64, 63, 62, 61, 60],
        [74, 73, 72, 71, 70]]])

In [31]:
a[2,0,0:]

array([50, 51, 52, 53, 54])