# 6.1 Tutorial Overview
This tutorial is divided into 4 parts; they are:
1. Limitation with Array Arithmetic
2. Array Broadcasting
3. Broadcasting in NumPy
4. Limitations of Broadcasting

### 6.2 Limitation with Array Arithmetic

### 6.3 Array Broadcasting

## 6.4 Broadcasting in NumPy

## 6.4.1 Scalar and One-Dimensional Array

In [1]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


### 6.4.2 Scalar and Two-Dimensional Array

In [3]:
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
    [1, 2, 3],
    [4, 5, 6]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [4 5 6]]
2
[[3 4 5]
 [6 7 8]]


### 6.4.3 One-Dimensional and Two-Dimensional Arrays

In [8]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
    [1, 2, 3],
    [1, 2, 3]])
print(A)
# define one-dimensional array
B = array([1, 2, 3])
print(B)
# broadcast
C = A + B
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [13]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
    [1, 2, 3,4],
    [1, 2, 3,4]])
print(A)
# define one-dimensional array
B = array([1, 2, 3, 4])
print(B)
# broadcast
C = A + B
print(C)

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[[2 4 6 8]
 [2 4 6 8]]


### 6.5 Limitations of Broadcasting

In [7]:
# broadcasting error
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = array([1, 2])
print(b.shape)
# attempt broadcast
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### 6.8 Summary