- N-dimensional arrays or the ndarray
- the main data structure used in machine learning

## 4.1 Tutorial Overview
This tutorial is divided into 3 parts; they are:
1. NumPy N-dimensional Array
2. Functions to Create Arrays
3. Combining Arrays

# 4.2 NumPy N-dimensional Array

In [1]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [4]:
import numpy as np

a = np.array(np.arange(1,4), dtype=np.float64)
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


# 4.3 Functions to Create Arrays

In [5]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[6.91849442e-310 6.91849442e-310 6.91849435e-310]
 [6.91849435e-310 6.91849435e-310 6.91849435e-310]
 [6.91849435e-310 6.91849436e-310 6.91849436e-310]]


In [6]:
print(a.shape)
print(a.dtype)
print(a.ndim)

(3, 3)
float64
2


In [7]:
import numpy as np

a = np.empty((3,3))
a

array([[6.91849442e-310, 6.91849442e-310, 6.91849435e-310],
       [6.91849435e-310, 6.91849435e-310, 6.91849435e-310],
       [6.91849435e-310, 6.91849436e-310, 6.91849436e-310]])

## 4.3.2 Zeros

In [8]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np

a = np.zeros((3,5)).astype(np.int64)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
a = np.zeros((3,5), dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
import numpy as np
a=np.zeros([3,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 4.3.3 Ones

In [13]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [14]:
import numpy as np
a=np.ones([5])
a

array([1., 1., 1., 1., 1.])

In [18]:
a=np.zeros((9,5),dtype=int)+125
a

array([[125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125]])

## 4.4 Combining Arrays

### 4.4.1 Vertical Stack

In [19]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
import numpy as np

a1=np.array([1,2,3])
a2=np.array([4,5,6])

a3=np.vstack((a1,a2))
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a1 = np.array([[1,2,3]])
a2 = np.array([[4,5,6]])
a3 = np.concatenate([a1,a2], axis=0)
a3

array([[1, 2, 3],
       [4, 5, 6]])

### 4.4.2 Horizontal Stack

In [22]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


In [23]:
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.hstack((a1,a2))
print(a3.shape)
a3

(6,)


array([1, 2, 3, 4, 5, 6])

In [24]:
a3 = np.concatenate([a1,a2])
a3

array([1, 2, 3, 4, 5, 6])

### 4.7 Summary