In [1]:
# Axis 1 and elements length is 3
[1, 2, 1]

[1, 2, 1]

In [2]:
[[ 1., 0., 0.],
 [ 0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

- class ndarray and alias array
- <b>numpy.array</b> not similar <b>array.array</b>
- The more important attributes of an ndarray object are:
    - ndarray.ndim (number of dimension)
    - ndarray.size (number of elements)
    - ndarray.dtype (return data type)
    - ndarray.itemsize (For example, an array of elements of type float64 has itemsize 8 (=64/8))
    - ndarray.data (the buffer containing the actual elements of the array.)

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
print("ndarray.ndim ", a.ndim)
print("ndarray.size ", a.size)
print("ndarray.dtype ", a.dtype)
print("ndarray.itemsize ", a.itemsize)
print("ndarray.data ", a.data)

ndarray.ndim  2
ndarray.size  15
ndarray.dtype  int64
ndarray.itemsize  8
ndarray.data  <memory at 0x7fb55014fa68>


# Array Creation

In [5]:
import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

[2 3 4]
int64


In [6]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [7]:
b=np.array([1,2,3,4,5,2.4])
b.dtype

dtype('float64')

In [8]:
# a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT

In [9]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array( [ [1,2], [-3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [-3.+0.j,  4.+0.j]])

In [11]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
np.empty( (2,3) )  #uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [15]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [16]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# See also

array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile


# Printing Arrays

In [18]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [19]:
b = np.arange(12).reshape(4,3)           # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
c = np.arange(24).reshape(2,3,4)         # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [22]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using <b>set_printoptions.</b>

In [23]:
np.set_printoptions(threshold=np.nan)
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

# Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [24]:
a = np.array( [20,30,40,50])
b = np.arange( 4 )
print(a)
print(b)


[20 30 40 50]
[0 1 2 3]


In [25]:
c = a-b
c

array([20, 29, 38, 47])

In [26]:
b**2

array([0, 1, 4, 9])

In [27]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [28]:
a<35

array([ True,  True, False, False])

In [29]:
a

array([20, 30, 40, 50])

In [30]:
a[a<35]

array([20, 30])

In [31]:
i = np.arange(3*50*50).reshape(3,50,50)
i[(i%3==0)&(i%5==0)&(i%7==0)]

array([   0,  105,  210,  315,  420,  525,  630,  735,  840,  945, 1050,
       1155, 1260, 1365, 1470, 1575, 1680, 1785, 1890, 1995, 2100, 2205,
       2310, 2415, 2520, 2625, 2730, 2835, 2940, 3045, 3150, 3255, 3360,
       3465, 3570, 3675, 3780, 3885, 3990, 4095, 4200, 4305, 4410, 4515,
       4620, 4725, 4830, 4935, 5040, 5145, 5250, 5355, 5460, 5565, 5670,
       5775, 5880, 5985, 6090, 6195, 6300, 6405, 6510, 6615, 6720, 6825,
       6930, 7035, 7140, 7245, 7350, 7455])

In [32]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [33]:
A * B

array([[2, 0],
       [0, 4]])

In [34]:
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [35]:
A @ B

array([[5, 4],
       [3, 4]])

In [36]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [37]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [38]:
b += a
b

array([[3.41628229, 3.4851852 , 3.03778684],
       [3.20798319, 3.87544296, 3.88481434]])

In [39]:
a += b  

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(a)
print(b)
print(b.dtype.name)

In [ ]:
c = a+b
c

In [ ]:
c.dtype.name

In [ ]:
d = np.exp(c*1j)
d

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [ ]:
a = np.random.random((2,3))
a

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
b = np.arange(12).reshape(3,4)
b

In [ ]:
b.sum(axis=0)

In [ ]:
b.min(axis=1)

In [ ]:
print(b)
b.cumsum(axis=1)

In [ ]:
b.min(axis=1)                            # min of each row

In [ ]:
b.cumsum(axis=1)                         # cumulative sum along each row

# Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [ ]:
B = np.arange(3)
B

In [ ]:
np.exp(B)

In [ ]:
np.sqrt(36)

In [ ]:
C = np.array([2., -1., 4.])
C

In [ ]:
np.add(B, C)



See also

all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where


In [ ]:
print(np.all([True, True, True]))
np.all([True, False, True])

In [ ]:
print(np.any([True, True, True]))
np.any([True, False, True])

In [ ]:
np.apply_along_axis??

In [ ]:
def func(x):
    return x+2

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

In [ ]:
np.apply_along_axis(func, 0, b)

In [ ]:
np.apply_along_axis(func, 1, b)

In [ ]:
a = np.array([1,2,5,6,8,3,2,6,7,2,4])
a

In [ ]:
np.argmax(a)

In [ ]:
np.argmin(a)

In [ ]:
np.argsort([1,7,7,3])

In [ ]:
np.ceil([1.2,3.7,7.2])

In [ ]:
a=np.array([1,2,3])
b=np.array([3,4,5])

np.cov(a,b)

# Indexing, Slicing and Iterating

In [ ]:
a = np.arange(10)**3
a

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

In [ ]:
a[ : :-1] 

In [ ]:
for i in a:
    print(i**(1/3.))

<b>Multidimensional arrays</b></br> can have one index per axis. These indices are given in a tuple separated by commas:

In [ ]:
def f(x,y):
    return x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

In [ ]:
np.fromfunction??

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

In [ ]:
np.fromfunction(lambda i, j: i+j, (3,3))

In [ ]:
b[2,3]

In [ ]:
b[0:5, 1]                       # each row in the second column of b

In [ ]:
print(b)
b[ : ,1]

In [ ]:
print(b)

b[1:3, : ]                      # each column in the second and third row of b

In [ ]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

In [ ]:
print(b)
b[0,...]

In [ ]:
b[...,1]

In [ ]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

In [ ]:
c[1,...]                                   # same as c[1,:,:] or c[1]

In [ ]:
print(c)
c[...,2] 

Iterating over multidimensional arrays is done with respect to the first axis:

In [ ]:
print(b)

for row in b:
    print(row)

In [ ]:
for element in b.flat:
    print(element)

# Shape Manipulation

In [ ]:
a = np.floor(10*np.random.random((3,4)))
a

three commands all return a modified array, but do not change the original array:

In [ ]:
a.ravel()  # returns the array, flattened

In [ ]:
a.reshape(6,2)  # returns the array with a modified shape

In [ ]:
a.T  # returns the array, transposed

In [ ]:
a.T.shape

In [ ]:
a.shape

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [ ]:
a

In [ ]:
a.resize((2,6))
a

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [ ]:
a.reshape(3,-1)

In [ ]:
a

In [ ]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

In [ ]:
np.resize(a,(1,4))

In [ ]:
np.resize(a,(2,4))

In [ ]:
print(a)

In [ ]:
b=a.ravel()
print(b)
b[0]=20
print(b)
print(a)

In [ ]:
c=a.flatten()
print(c)
c[0]=400
print(c)
a

# Stacking together different arrays

Several arrays can be stacked together along different axes:

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

In [ ]:
b = np.floor(10*np.random.random((2,2)))
b

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

In [ ]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

In [ ]:
np.hstack((a,b))           # the result is different

In [ ]:
print(a)
a[:,newaxis]               # this allows to have a 2D columns vector

In [ ]:
print(b)
b[:,newaxis]  

In [ ]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

In [ ]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)

In [ ]:
np.r_[1:4,0,4]



See also<br>

hstack, vstack, column_stack, concatenate, c_, r_


# Splitting one array into several smaller ones

In [ ]:
a = np.floor(10*np.random.random((2,12)))
a

In [ ]:
np.hsplit(a,3)   # Split a into 3

In [ ]:
print(a)
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

In [ ]:
np.vsplit(a, 2)

In [ ]:
np.split(a, 2,axis=0)

In [ ]:
np.split(a, 3, axis=1)

# Copies and Views

## No Copy at All

In [ ]:
a = np.arange(12)
b = a
a is b

In [ ]:
print(b)
b.shape = 3,4    # changes the shape of a
b

### Python passes mutable objects as references, so function calls make no copy.

In [ ]:
def f(x):
    print(id(x))
    
id(a)                           # id is a unique identifier of an object

In [ ]:
f(a)

## View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [ ]:
c = a.view()
c is a

In [ ]:
c.base is a                        # c is a view of the data owned by a

In [ ]:
c.flags.owndata


In [ ]:
c.shape = 2,6                      # a's shape doesn't change
c.shape

In [ ]:
c[0,4] = 1234                      # a's data changes
a

Slicing an array returns a view of it:

In [ ]:
print(a)
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s

In [ ]:
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
s

In [ ]:
a

## Deep Copy

The copy method makes a complete copy of the array and its data.

In [ ]:
d = a.copy()                          # a new array object with new data is created

In [ ]:
d is a

In [ ]:
d.base is a                           # d doesn't share anything with a

In [ ]:
d[0,0] = 9999
a

# Functions and Methods Overview

Indexing with Arrays of Indices

In [ ]:
a = np.arange(12)**2                       # the first 12 square numbers

In [ ]:
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices

In [ ]:
a[i]                                       # the elements of a at the positions i

In [ ]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
j

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
i = np.array( [ [0,1],                        # indices for the first dim of a
               [1,2] ] )
i

In [ ]:
j = np.array( [ [2,1],                        # indices for the second dim
               [3,3] ] )
j

In [ ]:
print(a)
print(i)
print(j)
a[i,j]                                     # i and j must have equal shape

In [ ]:
a[i,2]

Another common use of indexing with arrays is the search of the maximum value of time-dependent series:

In [ ]:
time = np.linspace(20, 145, 5)                 # time scale
data = np.sin(np.arange(20)).reshape(5,4)      # 4 time-dependent series

print(time)
data

In [ ]:
ind = data.argmax(axis=0)                  # index of the maxima for each series
ind

In [ ]:
time_max = time[ind]                       # times corresponding to the maxima
time_max

In [ ]:
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...

In [ ]:
data_max

In [ ]:
np.all(data_max == data.max(axis=0))

You can also use indexing with arrays as a target to assign to:

In [ ]:
a = np.arange(5)
a

In [ ]:
a[[1,3,4]] = 0
a

In [ ]:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

In [ ]:
a = np.arange(5)
a[[0,0,2]]+=1
a

In [ ]:
a = np.arange(12).reshape(3,4)
b = a > 4
b

In [ ]:
a[b]

In [ ]:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a

# Linear Algebra

In [ ]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

In [ ]:
a.transpose()

In [ ]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j

In [ ]:
np.trace(u)  # trace

In [ ]:
x=np.eye(7)
np.trace(x)

In [ ]:
a = np.arange(30)
a.shape = 2,-1,3  # -1 means "whatever is needed"
a.shape

In [ ]:
a

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,10000)
# Plot a normalized histogram with 50 bins
plt.hist(v, bins=50, density=1)       # matplotlib version (plot)
plt.show()

In [ ]:
# Compute the histogram with numpy and then plot it
(n, bins) = np.histogram(v, bins=50, density=True)  # NumPy version (no plot)
plt.plot(.5*(bins[1:]+bins[:-1]), n)
plt.show()

In [ ]:
i=np.arange(500).reshape(5,10,10)
i

In [ ]:
i[[4,0,2,3,1],::2,::-1][[0,-1]]
